In [26]:
import pickle as pk
import pandas as pd
import numpy as np

In [27]:
# opening or loading the pickle files

ohe_sex = pk.load(open('ohe_sex.pkl', 'rb'))
ohe_embarked = pk.load(open('ohe_embarked.pkl', 'rb'))
dtc = pk.load(open('model.pkl', 'rb'))

In [28]:
# here we are providing the testing data

test_data = np.array([2, 'male', 31.0, 0, 0, 10.5, 'Q'], dtype=object).reshape(1, 7)

In [29]:
test_data

array([[2, 'male', 31.0, 0, 0, 10.5, 'Q']], dtype=object)

In [42]:
# here we are encoding the sex column from ohe_sex

test_data_sex = ohe_sex.transform(test_data[:, 1].reshape(1, 1))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [31]:
test_data_sex.toarray()

array([[0, 1]], dtype=int32)

In [43]:
# here we are encoding the embarked column from ohe_embak=rked

test_data_embarked = ohe_embarked.transform(test_data[:, -1].reshape(1, 1))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [33]:
test_data_embarked.toarray()

array([[0, 1, 0, 0]], dtype=int32)

In [44]:
# here we are fetching the age column form test_data

test_data_age = test_data[:, 2].reshape(1, 1)

In [35]:
test_data_age

array([[31.0]], dtype=object)

In [36]:
test_data

array([[2, 'male', 31.0, 0, 0, 10.5, 'Q']], dtype=object)

In [38]:
# here we are again concatenating the remainig columns of test_data, test_data_age, test_data, sex, test_data_embarked columns

test_data_transform = np.concatenate((test_data[:, [0, 3, 4, 5]], test_data_age, test_data_sex.toarray(), test_data_embarked.toarray()), axis = 1)

In [40]:
test_data_transform.shape

(1, 11)

In [41]:
dtc.predict(test_data_transform)

array([1])